# increase sever performance
[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=$GAME_FPS
LanServerMaxTickRate=$GAME_FPS

[/Script/SocketSubsystemEpic.EpicNetDriver]
NetServerMaxTickRate=$GAME_FPS
LanServerMaxTickRate=$GAME_FPS

[/Script/Engine.Engine]
NetClientTicksPerSecond=$GAME_FPS
